### ISSUE TITLE
Persist the zoom level

### ISSUE THREAD

**Issue by ddstevens** [baffler/Transparent-Twitch-Chat-Overlay#12]
Excellent app thanks!

Could you make the zoom level persist between restarts?  If that is problematic can you provide an easier (less steps) way to adjust it?

**Comment by baffler** [comment]
It's supposed to persist, I'll look into why it's not. And yea the next version will have an easier way to adjust it.

**Comment by baffler** [comment]
Should be fixed with v0.6. There was an issue with it not saving if you zoomed out from default. It's also easier to adjust it, simply right-click on the black border at top, and it won't close the menu now when you increase/decrease the zoom. Feel free to open the issue again if the zoom level isn't persisting.
