### ISSUE TITLE
literally cant edit settings 

### ISSUE THREAD

**Issue by Bruhseve** [baffler/Transparent-Twitch-Chat-Overlay#138]
i minimized the border on the program so the annoying overlay didnt show and its just the chat, i now CANT open the settings at all and its really frusturating.

**Comment by Portaluke** [comment]
You'll need to bring the border back in order to interact with the chat window, however there's another way to access settings.
To bring back the border, bring the app into focus by clicking the taskbar icon and hitting F9. 
You may also use the system tray to access the settings or show/hide the border. (as seen below)
![PIPt7ABuzf](https://user-images.githubusercontent.com/58648868/194720129-e5eb1a05-03bf-4130-bea1-ffe0293a6325.png)
Hopefully this helps.
