### ISSUE TITLE
Unable to login to twitch through the overlay

### ISSUE THREAD

**Issue by Portaluke** [baffler/Transparent-Twitch-Chat-Overlay#139]
I haven't seen anyone else talking about this so I'm uncertain if it's just me having this issue (and why), however, any attempt to log into twitch through the overlay results in a "something went wrong" error. I made sure I had logged in properly by using another browser and it worked just fine. I'm wondering if there are files that remain when I uninstall (such as appdata or registry files) that I should try getting rid of for a fresh boot experience (as I did use this rarely in the past without issue). 

I'm in V0.92 and I do use 2FA with twitch (in case this matters).
Another (minor) issue is that the betterttv plugin is not working however I am slightly less concerned about that.

I left an image with the failed login and the debug file. I hope this all helps. 
(let me know if there's something you'd like to see or want me to try)
![ecAWlTKq4Q](https://user-images.githubusercontent.com/58648868/194719010-f8936616-7a4e-4cf5-9da6-2c33df886f10.png)

**Comment by StephenIz** [comment]
I am unable to log in, too. I get the same error. I tried installing the application on another computer which has never had the program installed before but still had the same issue, unfortunately.

**Comment by baffler** [comment]
I'm thinking it could just be that Chromium needs an update. I'll try putting in the latest version and see if it fixes it.

**Comment by baffler** [comment]
Not able to fix this, seems it's on Twitch. They are only supporting the major browsers now.
https://help.twitch.tv/s/article/supported-browsers?language=en_US

Found some more info about it here on this discussion.
https://discuss.dev.twitch.tv/t/login-not-working-in-chromium-cefsharp/41441

I guess they are blocking cefsharp (which is what my app uses) because it was being used by bots and other bad stuff.

**Comment by baffler** [comment]
The only workaround I've come across is that some people were able to login with a supported browser and copy the cookies/login session over to another browser. Not sure if this workaround will be possible here, but I'm labeling this as "help wanted" since I'm not sure if there's a solution out there right now for this sadly.

**Comment by baffler** [comment]
Did some testing and research today and a potential fix for this is maybe switching over to using WebView2 (Edge+Chromium) instead of just Chromium with CefSharp (what it's using now). I did some testing today and I'm able to get WebView2 to be transparent and behave like the current setup, and it let's you login to Twitch successfully!

**Comment by StephenIz** [comment]
That's great to hear! Thanks for taking the time to look into this.

**Comment by april83c** [comment]
> Did some testing and research today and a potential fix for this is maybe switching over to using WebView2 (Edge+Chromium) instead of just Chromium with CefSharp (what it's using now). I did some testing today and I'm able to get WebView2 to be transparent and behave like the current setup, and it let's you login to Twitch successfully!

did this change ever get pushed? still getting it

**Comment by april83c** [comment]
> > > Did some testing and research today and a potential fix for this is maybe switching over to using WebView2 (Edge+Chromium) instead of just Chromium with CefSharp (what it's using now). I did some testing today and I'm able to get WebView2 to be transparent and behave like the current setup, and it let's you login to Twitch successfully!
> > 
> > 
> > did this change ever get pushed? still getting the error
> 
> I had released a test version on the discord. Though I haven't really gotten any feedback from it yet, so I can probably release that version here. The only thing is I don't have a solution for a new installer yet. I'm trying to switch to an installer that's a little bit more reliable than the last.

i ended up building it myself and it seems to work good, login works :)

**Comment by baffler** [comment]
> i ended up building it myself and it seems to work good, login works :)

Appreciate the feedback. I just put up [v0.10.0](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.10.0) if anyone else wants to try it out as well. I'll have an installer for it ASAP
