### ISSUE TITLE
cant get rid of the cookie menu on the twitch overlay screen

### ISSUE THREAD

**Issue by ReapedRussianx** [baffler/Transparent-Twitch-Chat-Overlay#164]
i have watched several videos and tutorials and cannot get rid of the accept cookies menu

**Comment by timnl90** [comment]
@baffler I have the same issue. It happens if you change "Kapchat (default)" to "Twitch Popout".
You get in the above bar the cookies message, if you press "accept cookies" nothing happens and the message stays.

![cookies](https://user-images.githubusercontent.com/128744565/227330765-e36a4775-89c5-469b-87df-2997852be054.png)

**Comment by baffler** [comment]
I never could reproduce it, I just never saw the message to accept cookies ever popup. But I think this shouldn't be an issue with the next version that will use WebView2, I've had a lot better results with the new browser type in a lot of areas (like being able to login to Twitch finally). I also added an overlay on top of the browser source that should allow for better click detection for the underlying component too.
