### ISSUE TITLE
Doesnt work with Cyberpunk 2077

### ISSUE THREAD

**Issue by shoogo242** [baffler/Transparent-Twitch-Chat-Overlay#170]
When I start the game up the twitch overlay works fine, but as soon as I tab out and tab back into the game the overlay is gone, I have tried running the twitch chat overlay as administrator and also in win8 compatibility mode but neither of these two fixes the problem

**Comment by evgeniimv** [comment]
+1

**Comment by evgeniimv** [comment]
@shoogo242 
There is one workaround which helped me.
1) You need to install PowerToys by Microsoft https://learn.microsoft.com/en-us/windows/powertoys/install
It has [Always-on-Top](https://learn.microsoft.com/en-us/windows/powertoys/always-on-top) feature which can be used for any opened window by combination of keys **⊞ Win+Ctrl+T**
2) Open Twitch Chat and press **⊞ Win+Ctrl+T** --> window will be marked with blue border and pinned to the top
3) Open Cyberpunk2077 (Chat will be on top as it worked before) 
4) Do Alt-Tab and go back to the game (!!!Twitch Chat will go away but no worries its okay)
5) Press **⊞ Win+Ctrl+T** again while in game - Twitch Chat should appear again. Simply it means any time you do Alt-Tab and go back to the game you need to press  **⊞ Win+Ctrl+T** to move Twitch Chat back to the top.

PS. 
You can remove borders and sound signal in PowerToys Always-on-Top Settings
![image](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/assets/48137680/965b5b01-7f88-4608-8841-1e2580e7cf68)

**Comment by praw-cmd** [comment]
Still not working for Valorant, did it show on top of other apps but I can't show it in valorant I guess vanguard is blocking it.

**Comment by baffler** [comment]
I was working on this, and I can get it to work like the power toys workaround, but I'm trying to find the best way to go about it. The only way to do it more automatic is by doing a timer that checks every so often, but this isn't ideal since it can kinda take focus away from other apps (like if you're typing somewhere). It seems finicky at best. I do think some key combination could work, maybe even looking for when you press Alt+Tab and it could push the app back on top?

**Comment by baffler** [comment]
So I have this working like the PowerToys solution @evgeniimv posted above. In [v1.0.0](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.0) you can press the F8 key and it will start a timer that forces the app to be on top, it will send it 3 times, within 3 seconds, so that if Cyberpunk or other games, try to take focus while switching, it will put it back on top. I've tested this in Cyberpunk and it works well. But just like the PowerToys, you have to press the key each time you alt-tab. I don't see a way around that issue yet, but if you don't alt-tab too much, it's not too much trouble to press the F8 key to get it back on top again 👍

**Comment by evgeniimv** [comment]
@baffler Thank you for your input! Glad to see this problem has found its solution 👏
