### ISSUE TITLE
Having issues with logging into twitch

### ISSUE THREAD

**Issue by MarvelDemon0** [baffler/Transparent-Twitch-Chat-Overlay#200]
With the chat extension it asked me to sign into twitch and once I tried logging in it had a message stating, "Your browser is not currently supported. Please use a recommended browser or learn more here."

**Comment by baffler** [comment]
Can see issue [#139](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/issues/139) about this. From what I've researched, Twitch put in measures for security reasons (supposedly to stop bots) to prevent Chromium from being used to login to Twitch. I have yet to find a workaround for this.

**Comment by baffler** [comment]
Did some testing and research today and a potential fix for this is maybe switching over to using WebView2 (Edge+Chromium) instead of just Chromium with CefSharp (what it's using now). I did some testing today and I'm able to get WebView2 to be transparent and behave like the current setup, and it let's you login to Twitch successfully!

**Comment by baffler** [comment]
[v0.10.0](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.10.0) will allow you to login now
