### ISSUE TITLE
Should we all just stop using this? 

### ISSUE THREAD

**Issue by goodworkriah** [baffler/Transparent-Twitch-Chat-Overlay#222]
This isn't working anymore and i'm not seeing any updates on fixes? Is it time to abandon ship?

**Comment by baffler** [comment]
It's still working for me. I'm not able to keep working on it but it's in my free time. If you had issues with v0.9.5 it was because the installer was broken, a re-install can fix it. However, I was making some big changes to [v0.10.0](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.10.0). I'm also looking into other installers that should be more reliable.
