### ISSUE TITLE
Doesn't show in certain games

### ISSUE THREAD

**Issue by IAmAProfessionalGamer** [baffler/Transparent-Twitch-Chat-Overlay#226]
I'm using this with The Hunter Call of the Wild and the chat overlay isn't visible in game.

**Comment by baffler** [comment]
There's some games that it just can't work in, due to technical limitations. However, there are some it _could_ work in but doesn't (like Cyberpunk). The issue is, it needs to keep sending out a signal to the OS that it should be on top. I'm thinking of making a global hotkey you could press to send that signal. This _might_ fix the issue with the game you mentioned, I'll update this when I add in the hotkey

**Comment by baffler** [comment]
In [v1.0.0](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.0) I added a global hotkey to force the app to be topmost, the hotkey is the F8 key. This might not work for all games, like games that are exclusive fullscreen, but it does work for others like Cyberpunk now, for example. You may have to press the key each time you alt-tab out and back into the game as well.
