### ISSUE TITLE
Little X button remains visible after toggling borders 

### ISSUE THREAD

**Issue by KalieMiler** [baffler/Transparent-Twitch-Chat-Overlay#235]
After toggling the borders the small X button in the top right of the window remains visible and does not get hidden like all the other border elements.

![Unbenannt](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/assets/159648620/d2bc6f53-8734-47ba-b2cb-c46c7e1841df)

**Comment by baffler** [comment]
Meant to put this under known issues. I actually spent quite some time trying to get rid of this little x, and gave up... for now! The issue was with the library I'm using to draw into the border area, and it handles the drawing of the system buttons. It's supposed to hide the "x" when I set the border to none, but I think it might be a bug. I'm looking into a workaround for it.

**Comment by DerrPHANTOM** [comment]
Seem to be multiple instances of this issue, so commenting here to keep up to date. Looking forward to this being sorted as I can't use the new version until it is sorted. Thanks for an awesome app.

**Comment by baffler** [comment]
This is fixed in [v1.0.4](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.4)
