### ISSUE TITLE
No options in the setup app.

### ISSUE THREAD

**Issue by GodSponge** [baffler/Transparent-Twitch-Chat-Overlay#241]
Is there any reason why there are no options at all for the setup app? I don't install apps to appdata, and really hate it when apps do it without asking. If it's not possible to allow for specifying the location on setup, will it break the app if I move the install folder?

**Comment by baffler** [comment]
Using Squirrel for installation and updates now. I guess it's sort of their philosophy to keep it simple, and the reasoning for installing to appdata is so users won't have to click any popup to allow access to install it. It probably won't break it to move it somewhere else, but I am planning on releasing a standalone version that I'll deploy as a zip file, so that way you can just extract it wherever you want.

**Comment by GodSponge** [comment]
I'm all for the standalone one. Thanks so much for the quick response (and the awesome app).
