### ISSUE TITLE
Join channel: Night

### ISSUE THREAD

**Issue by kuroganashi** [baffler/Transparent-Twitch-Chat-Overlay#279]
the app suddently joined a channel that isn't mine and refuses to work....

says 

Chat: Loading...
Chat: Connecting to Chat server...
Chat: Connected
Chat: Join channel night

**Comment by mrky99** [comment]
Bro, I have same issue, trying to reinstall and nothing happens

**Comment by MajesticalDiscomfort** [comment]
Same here. Reinstalled from the same installer I used a few weeks ago, but didn't fix the issue, even though it was working before. Twitch might have altered their chat webhook or something.

**Comment by abedthepro0** [comment]
so whats happening is the app is connecting to the chat "night" instead of the desired chat, annoying, theres a loophole tho, a little hard, a fix is needed tho

**Comment by GameswithDeath** [comment]
Same...

**Comment by Tempritscher** [comment]
same here. got bunch of porn messages

**Comment by albusGTI** [comment]
any solutions?  I need to start stream soon

**Comment by brailu** [comment]
same here :(
If anyone figures out how to fix it, please let us know.

**Comment by koiminoi** [comment]
the messages i saw were someone (ace something) saying that something was hacked.

**Comment by Tempritscher** [comment]
Open settings and use jChay (Beta) (Can linck it to your own channel

**Comment by Open420TTV** [comment]
this is still happening to me. jChat works but theres huge text on my screen saying "conencting to IRC server... jchat connected jchat joined channel#open_420,  and while other chat fades in 10 sec like i setup, this chat doesnt. any idea whats going on? my discord is   open420  add me if u wanna chat about this

**Comment by AppalachianTreasures** [comment]
anyone know or figure out how to fix this

**Comment by AppalachianTreasures** [comment]
It's a hacker he's changed the code completely to his channel and his channel only

**Comment by OriusKhan** [comment]
This guy showed how he fixed it in a few seconds. Someone else above says Twitch Popout works also, so the problem seems related to the default (KapChat).

https://clips.twitch.tv/SwissExcitedHippoTBTacoLeft-gDHp0jftYBbldsTT

**Comment by MichaelHeinzman** [comment]
Same

**Comment by baffler** [comment]
This wasn't a hack at all. It was a change with KapChat, apparently if the URL contains "www" for KapChat, it will now redirect, to basically the same page without the "www". The issue is, it will remove the parameters. So this URL 
`https://www.nightdev.com/hosted/obschat?theme=bttv_dark&channel=baffler&fade=false&bot_activity=false&prevent_clipping=false` 
will now take you to this 
`https://nightdev.com/hosted/obschat/`

It doesn't have the channel name anymore, so it defaults to "Night" because that is the developer of KapChat. I'll put out a fix soon, within the next 24 hours. For now you can use any of the other chats like jChat will work just fine.

**Comment by baffler** [comment]
Can try [v1.0.3](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.3)? Should work now

**Comment by SusgUY446** [comment]
> Can try [v1.0.3](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.3)? Should work now

works 👍
