### ISSUE TITLE
not my chatbox

### ISSUE THREAD

**Issue by AkiAbukara** [baffler/Transparent-Twitch-Chat-Overlay#280]
Hello i just get problem with my chat overlay, when i use my ID, in simply way ther is just not my chat, but still my ID

**Comment by Tempritscher** [comment]
this: https://github.com/baffler/Transparent-Twitch-Chat-Overlay/issues/279

**Comment by ratwinkyface** [comment]
i also am having this issue. I tried to uninstall and reinstall and it is the same issue. I even installed an earlier version but nothing. I'm hoping this gets fixed soon

**Comment by OriusKhan** [comment]
The problem seems to be with KapChat service, not this software specifically. So reinstalling won't fix it, because KapChat is still the default. Changing the settings to use jChat or Twitch Popout instead seems to work fine.

This guy showed how he fixed it in a few seconds if you want to see the steps.

https://clips.twitch.tv/SwissExcitedHippoTBTacoLeft-gDHp0jftYBbldsTT

**Comment by baffler** [comment]
Can try [v1.0.3](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.3)? Should work now
