### ISSUE TITLE
Possibility of making the software more lightweight/rely on less dependencies

### ISSUE THREAD

**Issue by unRyker** [baffler/Transparent-Twitch-Chat-Overlay#39]
This is a suggestion that I hope you consider after you refine your wonderful program, perhaps after 0.7.1 or even after 0.8

I noticed that your program is almost 150MB total and the number one offender to filesize is libcef.dll and in addition to that, using Resource Monitor it appears that it's using 30 threads (which seems rather odd to me), when compared to Chocolate Doom it uses only 12 threads and it's a total of 10MB including the game data itself it requires to run. It also rivals Dolphin Emulator in terms of threads it uses to run emulated games (40 threads).

Since you are designing this for streamers in mind, I hope you consider or get help for tidying up your software so it has less performance impact and memory impact since streamers already have a lot of processes running.

I'm no programmer but I would love to know why it currently is the way it is and why the .dll I mentioned is a large size. I have a feeling it's because it's like a pinnable web browser but I would like more information on what it is exactly. Thank you for all your work!

**Comment by baffler** [comment]
The app uses CefSharp (chromium embedded into the .NET app) so the filesize is going to be high since it's essentially an entire browser that needs to be shipped with the app. The filesize really doesn't matter when it comes to performance though, the only thing that can possibly affect performance is CPU time and memory. I've tested the app in 50,000+ viewer streamer chats and it usually goes up to 1% CPU but a lot of times less. It usually stays about 70 to 80mb in the large streams as well (at the time, it was using as much as discord). Obviously, much smaller streams it uses less CPU and memory. The thing I did notice was GIFs can make it go to 2% CPU even in smaller streams, but even when I spammed lots of GIFs, it would max at 2%.

As far as threads, I can't say I know a lot about how they affect performance. I did google a bit and if anything, people said more threads = better performance actually. I created a blank WPF application in C# and with it literally doing nothing, the thread count was 25. But I really don't think the amount of threads matters that much, it's more about the CPU and memory footprint which my app seems to be pretty low already.
