### ISSUE TITLE
[question] Elements for custom css

### ISSUE THREAD

**Issue by christsironis** [baffler/Transparent-Twitch-Chat-Overlay#62]
1. Can i find somewhere the html code of the KapChat window. Because i'm trying to make my own custom CSS but i want to know all the elements that are inside the element with class:  chat_box.
I know that there are some defaults like the  .chat_line .message / .chat_line .nick / .chat_line 
but i need to know more details about the html.

2.  And is it possible to make changes on the html of the KapChat?

**Comment by baffler** [comment]
https://nightdev.com/kapchat/ Click the "get it" button and it will just generate a URL for you. Go to the URL in chrome or whatever browser you use and open your developer tools for the browser. That's how I've been doing it.

Not really possible with my program, at least I haven't added the ability. It's technically possible because you can execute javascript with CEF but I haven't added anything to allow that from the user.
