### ISSUE TITLE
Laptop issue

### ISSUE THREAD

**Issue by fawns2346** [baffler/Transparent-Twitch-Chat-Overlay#66]
So I can read the chat while streaming on my laptop but it still isn't showing up in the actual stream itself, I have a slight idea of what the issue may be but there isn't anything I can do about it since I couldn't use OBS due to having two GPU's and not having what I needed on my laptop in order to pick one , and I have extremely limited knowledge in doing what would be necessary to fix it. 
I am currently using twitch Studio's to stream on due to the GPU issue. I've been basically trouble shooting this with a friend for the past 3 days ad neither of us are sure what it could be that is causing the issue.

**Comment by baffler** [comment]
The reason it doesn't show up is because it's doing a game capture, which won't show anything that is over it. But it's not really supposed to show up, it was meant just so you can read chat without having to use your phone or whatever (which you couldn't capture either :P). Technically you can do a window capture of the chat program but it won't be transparent, it's best to just go into your scene, click Edit Scene button at bottom, add a new layer and use the built in chat box there, or you can choose to add Browser Source and then go to https://nightdev.com/kapchat/ and generate a URL for your channel. KapChat is what my program uses so it will basically be the same.
